#!/bin/sh

if [ ! -z "$DEBUG" ] && [ "$DEBUG" ]; then
    set -x
fi

declare -r APP_NAME="wannaBuild"
declare -r APP_VERSION="0.1"

if [ -f "/etc/default/DeBaBaReTools" ]; then
        . /etc/default/DeBaBaReTools
fi

if [ -f "$HOME/.DeBaBaReToolsrc" ]; then
        . "$HOME/.DeBaBaReToolsrc"
fi

if [ -f "/etc/default/$APP_NAME" ]; then
	. /etc/default/$APP_NAME
fi

if [ -f "$HOME/.${APP_NAME}rc" ]; then
        . "$HOME/.${APP_NAME}rc"
fi

. $BACKEND_DIR/probe.sh

# we first load the settings
probeFile "config"

cd "$BASE_DIR"

# afterwards we load the rest
probeFile "lock" "startup" "setDefault" "verbosity"

lockApplication

setDefault "VERBOSE" "0"
setDefault "PBUILDER_CACHE" "/var/cache/pbuilder"
setDefault "BUILD_DIR" "build"
setDefault "BUILD_DATA" "$BUILD_DIR/data"
setDefault "UPDATE_TGZ" "1"
setDefault "GAINROOT" "sudo"

if verbose; then
	sayHello
fi

set +e

for LIST in $BUILD_DATA/*; do
    if [ ! -f $LIST ]; then
        continue
    fi

    checkUnlock

    DISTRO="`echo "$LIST" | awk -F. '{ print $2 }'`"

    Say "Processing packages to be built for $DISTRO"

    if [ $UPDATE_TGZ -gt 0 ]; then
        Say "Executing pbuilder --update --basetgz ${PBUILDER_CACHE}/${DISTRO}.tgz"
        
        $GAINROOT pbuilder --update --basetgz ${PBUILDER_CACHE}/${DISTRO}.tgz > $BUILD_DIR/logs/${DISTRO}.update
    else
        Say "Not updating ${PBUILDER_CACHE}/${DISTRO}.tgz, as requested"
    fi

    for PACKAGE_L in `cat $LIST`; do
        S_PACKAGE="`echo "$PACKAGE_L" | awk '-F|' '{ print $1 }'`"
        Arch="`echo "$PACKAGE_L" | awk '-F|' '{ print $2 }'`"

	checkUnlock

        Say  "\tProcessing source package $S_PACKAGE"

        if [ "$Arch" != "${DEB_BUILD_ARCH}" ]; then
            Say  "\tIgnoring entry: $PACKAGE_L (not a good arch)"
            continue
        fi

        if [ ! -f "${ACCEPTED}/${S_PACKAGE}.dsc" ]; then
            Say "\tRemoving entry: $PACKAGE_L (file not found)"
            
            sed --in-place "s/${PACKAGE_L}//;" $BUILD_DATA/needsBuild.${DISTRO}
            sed --in-place "s/${S_PACKAGE}|all//;" $BUILD_DATA/needsBuild.${DISTRO}
            continue
        fi

        #BUILDOPTS="-a${DEB_BUILD_ARCH} -t${DEB_BUILD_GNU_TYPE} -b"
        BUILDOPTS=""
        PBUILDEROPTS=""
        BUILDALL=0

        #
        # Check whether we are building binary-arch or also include indep
        #
        if [ -z "`cat $LIST | grep "$S_PACKAGE|all"`" ]; then
            PBUILDEROPTS+=' --binary-arch'
        else
            BUILDALL=1
            Say "\t\tAlso going to build 'all'"
        fi

        #
        # Create a temp dir where the results are going to be placed after building
        # TODO: fix this thing!!! pdebuilder should be called
        RESULTSDIR=`mktemp -d -p $BUILD_DIR/ XXXXXXXXXXX` || exit 1

        Say "\t\tStarting pbuilder --build ${PBUILDEROPTS} --debbuildopts ${BUILDOPTS} --buildresult ${RESULTSDIR} --basetgz ${PBUILDER_CACHE}/${DISTRO}.tgz ${ACCEPTED}/${S_PACKAGE}.dsc"

        #
        # Finally build
        #  pdebuild/pbuilder options must be setup in the pbuilderrc file
        #
        $GAINROOT pbuilder --build ${PBUILDEROPTS} --debbuildopts "${BUILDOPTS}" --buildresult ${RESULTSDIR} --basetgz ${PBUILDER_CACHE}/${DISTRO}.tgz ${ACCEPTED}/${S_PACKAGE}.dsc > $BUILD_DIR/logs/$S_PACKAGE 2> $BUILD_DIR/logs/$S_PACKAGE.error

        #
        # Make sure we got something
        #

        if [ ! -f "${RESULTSDIR}/${S_PACKAGE}_${Arch}.changes" ]; then
            Say "\t\tCould not find ${RESULTSDIR}/${S_PACKAGE}_${Arch}.changes, build failed"
            
            echo "${PACKAGE_L}" >> $BUILD_DATA/failedToBuild.${DISTRO}
            sed --in-place "s/${PACKAGE_L}//;" $BUILD_DATA/needsBuild.${DISTRO}
            sed --in-place "s/${S_PACKAGE}|all//;" $BUILD_DATA/needsBuild.${DISTRO}
            continue
        fi

        FILES="`cat ${RESULTSDIR}/${S_PACKAGE}_${Arch}.changes | egrep "[0-9a-f]{32} [0-9]+ [a-z]+ [a-z]+ .*\.deb" | sed "s/ /|/g;"`"
        for FEntry in $FILES; do
            if [ -z "$FEntry" ]; then
                continue
            fi

            F="`echo "$FEntry" | awk '-F|' '{ print $6 }'`"

            Say "\t\tInstalling ${RESULTSDIR}/$F in $INCOMING/${DISTRO}/"

            mv ${RESULTSDIR}/$F $INCOMING/${DISTRO}/
        done

        Say "\t\tInstalling ${RESULTSDIR}/${S_PACKAGE}_${Arch}.changes in $INCOMING/${DISTRO}/"

        mv ${RESULTSDIR}/${S_PACKAGE}_${Arch}.changes $INCOMING/${DISTRO}/

        sed --in-place "s/${PACKAGE_L}//;" $BUILD_DATA/needsBuild.${DISTRO}
        sed --in-place "s/${S_PACKAGE}|all//;" $BUILD_DATA/needsBuild.${DISTRO}

        FilesInBuild="`ls ${RESULTSDIR}/*`"
        Say "\t\tCleaning results directory (${RESULTSDIR}):"

        for F in "$FilesInBuild"; do
            F="${RESULTSDIR}/${F}"
            Say "\t\trm -rf $F"
            rm -rf $F
        done
        rm -rf ${RESULTSDIR}

    done
done

unlockApplication
exit 0
