#!/bin/sh

if [ ! -d "admin" ]; then
	echo "cd to the right directory before running"
	exit 1
fi

if [ -f ENV ]; then
	mv ENV ENV.bak
fi

echo -e "ENVIRONMENT variables list/documentation generated by admin/genENV.sh\n" > ENV

egrep -r "[#]+[ \t]*ENV[:]?[ \t]*" ./ | \
	egrep -v "^admin/" | \
	grep -v "/.svn/" | \
	grep -v '~:' | \
	grep -v '.bak:' | \
	grep -v "/default.sh" | \
	sed -r "s/([#]+[ \t]*ENV[:]?[ \t]*)/ /g" | \
	sed -r "s/([ \t]+)/ /g" | \
	cut '-d:' '-f2-' | \
	sort -ui | \
	sed "s%^\./%%;s/^ //" \
	>> ENV
