#!/bin/sh

set -e

if [ ! -d "admin" ]; then
	echo "cd to the right directory before running"
	exit 1
fi

tmp="$(mktemp -p .)"

files="$(find . -type f ! -name *~ -a ! -name '*.bak' -a ! -path '*/admin/*' \
		-a ! -path '*/debian/*' -a ! -path '*/.*' -a ! -name 'tmp*')"

for f in $files; do
    sed -e :a -e '$!N;s/\n#\./ /;ta' -e 'P;D' "$f" | \
	egrep "^[ \t]*#+[ \t]*ENV:?[ \t]*" | \
	sed -r "s/#+[ \t]*ENV:?[ \t]*/ /g" | \
	sed -r "s/[ \t]+/ /g" | \
	sed "s%^\./%%;s/^ //" \
	    >> $tmp
done

if [ -f ENV ]; then
	mv ENV ENV.bak
fi

printf "ENVIRONMENT variables list/documentation generated by admin/genENV.sh\n\n" > ENV

cat $tmp | sort -ui >> ENV
rm $tmp
