#!/bin/sh

if [ ! -d "admin" ]; then
	echo "cd to the right directory before running"
	exit 1
fi

if [ -f TODO ]; then
	mv TODO TODO.bak
fi

echo -e "TODO list generated by admin/genTODO.sh\n" > TODO

egrep -r "[#]+[ \t]*TODO[:]?[ \t]*" ./ | \
	egrep -v "^admin/" | \
	grep -v "/.svn/" | \
	grep -v '~:' | \
	grep -v '.bak:' | \
	grep -v "/default.sh" | \
	sed "s%^\./%%" \
	>> TODO
