#!/bin/sh

set -e

if [ ! -d "admin" ]; then
	echo "cd to the right directory before running"
	exit 1
fi

tmp="$(mktemp -p .)"

files="$(find . -type f ! -name *~ -a ! -name '*.bak' -a ! -path '*/admin/*' \
		-a ! -path '*/debian/*' -a ! -path '*/.*' -a ! -name 'tmp*')"

for f in $files; do
    l="$(sed -e :a -e '$!N;s/\n#\./ /;ta' -e 'P;D' "$f" | \
	egrep "^[ \t]*#+[ \t]*TODO:?[ \t]*" | \
	sed -r "s/#+[ \t]*TODO:?[ \t]*/ /g" | \
	sed -r "s/[ \t]+/ /g" | \
	sed "s%^\./%%;s/^ //" )" #"
    [ "$l" ]  && printf "%s: %s\n" "$(echo "$f" | sed "s#./##")" "$l" >> $tmp
done

if [ -f TODO ]; then
	mv TODO TODO.bak
fi

printf "TODO list generated by admin/genTODO.sh\n\n" > TODO

cat $tmp | sort -ui >> TODO
rm $tmp
